# Generated by Django 5.1.5 on 2025-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sot_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sot',
            name='hostname',
            field=models.CharField(default='192.168.0.16', max_length=80),
        ),
    ]
