#!/bin/bash
# chkconfig: 345 01 99

### BEGIN INIT INFO
# Provides:          custom firewall
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: firewall initscript
# Description:       Custom Firewall
### END INIT INFO


# Execute:

# CentOS
# chmod 755 /etc/init.d/firewall && chkconfig --add firewall && chkconfig firewall on && chkconfig iptables off

# Debian/Ubuntu
# chmod 755 /etc/init.d/firewall && update-rc.d firewall start 01 2 3 4 5 . stop 99 0 1 6 .

###

RULES_FILE="/etc/default/firewall.inc"

RETVAL=0
# To start the firewall
function start() {

# Termina se não existe iptables
[ -x /sbin/iptables ] || exit 1

# Arquivo com as regras propriamente ditas
if [ -f "$RULES_FILE" ]; then
        echo "Carregando regras de firewall IPv4 ..."
        . $RULES_FILE
else
        echo "Arquivo de regras inexistente: ${RULES_FILE}."
        exit 1
fi
RETVAL=0
}

# To stop the firewall
function stop() {
  echo "Removendo as regras de firewall IPv4 e IPv6 ..."
  iptables -P INPUT ACCEPT
  iptables -F
  iptables -X
  iptables -Z
  RETVAL=0
}

case $1 in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    echo "============================== IPv4 =============================="
    /sbin/iptables -nL
    RETVAL=0
    ;;
  *)
    echo "Uso: $1 {start|stoprestart|status}"
    RETVAL=1;;
esac
exit $RETVAL
